import {mkdir,cp,writeFile,readFile,rm,access} from 'node:fs/promises';
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});await cp('public','dist',{recursive:true});
for(const file of ['facility-render-pass.js','map-selection.js','reactor-map.js','reactor-environment.js','maps/reactor/collision-data.js','maps/reactor/environment.json','maps/reactor/geometry.bin.gz','maps/reactor/UPSTREAM-LICENSE.md','maps/reactor/SOURCE.md','island-map.js','maps/ironwood/height-data.js','maps/ironwood/forest-data.js','maps/ironwood/SOURCE.md','maps/ironwood/Terrain3D-LICENSE.txt','maps/ironwood/Kenney-ASSET-LICENSE.md','deployment-cues.js','deployment-cinematic.js','deployment-cinematic.css','deployment-audio.js','audio/deployment-intro.mp3','weapon-audio.js','audio/ar-shot.wav','audio/shotgun-shot.wav','audio/shotgun-reload.wav','weapon-inventory.js','inventory-prediction.js','inventory-menu.js','inventory-menu.css','weapon-assets.js','world-chunks.js','app.js','engine.js','network.js','network-tuning.js','deployment-sequence.js','deployment-ship.js','character-animation.js','match-character-renderer.js','avatar-model.js','lobby-characters.js','weapon-model.js','render-buffer.js','simulation.js','connection-stability.js','multiplayer-runtime.js','build-grid.js','items.js','resource-system.js','loot-system.js','shockwave.js','world-layout.js','bullet-presentation.js','first-person-calibration.js','soldier-arms.js','held-items.js','movement-collision.js','visual-presentation.js','character-lighting.js','index.html'])await access('dist/'+file);
const url=process.env.SUPABASE_URL||'',key=process.env.SUPABASE_PUBLISHABLE_KEY||'';
if(key.startsWith('sb_secret_'))throw Error('Use a public Supabase publishable key, never a secret key.');
if(key.startsWith('eyJ')){try{const role=JSON.parse(Buffer.from(key.split('.')[1],'base64url')).role;if(role==='service_role')throw Error('Use the public anon or publishable key, never the service-role key.');}catch(e){if(e.message.includes('service-role'))throw e;}}
if((url&&!/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/.test(url))||(!url&&key)||(url&&!key))throw Error('SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY must be set together, using a valid Supabase project URL.');
const configTemplate=await readFile('public/config.js','utf8'),placeholder="window.HORIZON_CONFIG={url:'',key:''};";
if(!configTemplate.includes(placeholder))throw Error('public/config.js is missing the build configuration placeholder.');
await writeFile('dist/config.js',configTemplate.replace(placeholder,'window.HORIZON_CONFIG='+JSON.stringify({url,key})+';'));
console.log('Static app built. '+(url&&key?'Online presence, invites and private parties configured.':'Online multiplayer awaits Supabase URL and public key; same-browser invite testing is available.'));

for(const file of ['build/three.module.js','build/three.core.js','examples/jsm/loaders/GLTFLoader.js','examples/jsm/environments/RoomEnvironment.js','examples/jsm/utils/SkeletonUtils.js','examples/jsm/utils/BufferGeometryUtils.js','LICENSE']){const target='dist/vendor/three/'+file;await mkdir(target.slice(0,target.lastIndexOf('/')),{recursive:true});await cp('node_modules/three/'+file,target);}
