import test from 'node:test';
import assert from 'node:assert/strict';
import {Match} from '../public/simulation.js';
const world={height:()=>0,obstacles:[],resources:[{id:'tree',kind:'wood',x:0,y:0,z:-2,hp:100},{id:'rock',kind:'stone',x:3,y:0,z:0,hp:100}],chests:[{id:'chest',x:0,y:0,z:-2}]};
function match(){const m=new Match(world,['a','b'],'town');m.phase='playing';for(const [i,p] of m.players.entries()){p.p=[i*20,0,0];p.air='landed';p.deploymentState='match_active';p.slot=0;}return m;}
test('players start with pickaxe, no firearms, zero materials and shield',()=>{const p=match().players[0];assert.equal(p.shield,0);assert.deepEqual(p.materials,{wood:0,stone:0});assert.deepEqual(p.weapons,{});assert.equal(p.slot,0);});
test('unowned firearm cannot fire',()=>{const m=match(),p=m.players[0];p.slot=1;m.fireWeapon(p,{yaw:0,pitch:0,aimYaw:0,aimPitch:0},0);assert.equal(m.events.filter(e=>e.type==='shot').length,0);});
test('tree and rock grant distinct resources and depleted nodes grant nothing',()=>{const m=match(),p=m.players[0];for(let i=0;i<4;i++){p.cool=0;m.harvest(p,{yaw:0,pitch:0});}assert.equal(p.materials.wood,40);p.cool=0;m.harvest(p,{yaw:0,pitch:0});assert.equal(p.materials.wood,40);p.p=[3,0,2];for(let i=0;i<4;i++){p.cool=0;m.harvest(p,{yaw:0,pitch:0});}assert.equal(p.materials.stone,32);});
test('chest opens once and competing players cannot collect the same loot',()=>{const m=match(),p=m.players[0];m.interact(p,{yaw:0,pitch:0});const drops=m.pickups.map(v=>({...v}));assert.ok(drops.length>=2);m.interact(p,{yaw:0,pitch:0});assert.equal(m.openedChests.size,1);const item=m.pickups[0];p.p=[item.x,0,item.z+1];m.players[1].p=p.p.slice();assert.equal(m.collect(p,item.id),true);assert.equal(m.collect(m.players[1],item.id),false);const n=match();n.interact(n.players[0],{yaw:0,pitch:0});assert.deepEqual(n.pickups,drops);});
test('shield use completes after three seconds, grants 25 and cancels without loss',()=>{const m=match(),p=m.players[0];p.items.shield=3;p.slot=7;m.beginUse(p);m.advanceUse(p,2.99);assert.equal(p.shield,0);assert.equal(p.items.shield,3);m.advanceUse(p,.01);assert.equal(p.shield,25);assert.equal(p.items.shield,2);m.beginUse(p);p.slot=0;m.advanceUse(p,3);assert.equal(p.items.shield,2);});
test('health restores full health only after use completes',()=>{const m=match(),p=m.players[0];p.items.health=1;p.hp=21;p.slot=8;m.beginUse(p);m.advanceUse(p,4);assert.equal(p.hp,21);m.advanceUse(p,1);assert.equal(p.hp,100);assert.equal(p.items.health,0);});
