import test from 'node:test';
import assert from 'node:assert/strict';
import {Match,sanitize} from '../public/simulation.js';
import {groundWeaponPose,pickupPointInside} from '../public/pickup-targeting.js';
function fixture(){const m=new Match({height:()=>0,obstacles:[],resources:[],chests:[]},['a','b']);m.phase='playing';m.players[0].p=[0,0,0];m.players[0].air='landed';m.pickups=[{id:'displayed',type:'ar_sentinel',x:0,y:0,z:-2,count:1},{id:'neighbour',type:'smg_viper',x:.6,y:0,z:-1.5,count:1}];return {m,p:m.players[0]};}
const request=(id='displayed',revision=1)=>({revision,id,round:1,time:0,origin:[0,1.72,0],point:[0,.4,-2]});
test('E without a displayed pickup never collects a nearby weapon',()=>{const {m,p}=fixture();assert.equal(m.interact(p,sanitize({yaw:0,pitch:0,interact:true})),false);assert.equal(m.pickups.length,2);});
test('E collects the displayed instance instead of a nearer neighbour',()=>{const {m,p}=fixture();assert.equal(m.interact(p,sanitize({pickupRequest:request()})),true);assert.equal(p.inventory[0].type,'ar_sentinel');assert.equal(m.pickups[0].id,'neighbour');});
test('a removed displayed target never falls back to another pickup',()=>{const {m,p}=fixture();m.pickups.shift();assert.equal(m.interact(p,sanitize({pickupRequest:request()})),false);assert.equal(m.pickups.length,1);});
test('displayed target behind cover cannot be picked up',()=>{const {m,p}=fixture();m.world.obstacles=[{min:[-2,0,-1.5],max:[2,3,-1]}];assert.equal(m.interact(p,sanitize({pickupRequest:request()})),false);});
test('invalid or remote pickup rays are rejected and requests are sanitized',()=>{const {m,p}=fixture();assert.equal(m.interact(p,sanitize({pickupRequest:{...request(),origin:[100,1.72,0]}})),false);assert.equal(m.interact(p,sanitize({pickupRequest:{...request(),point:[20,0,-2]}})),false);assert.equal(sanitize({pickupRequest:{...request(),point:[NaN,0,0]}}).pickupRequest,null);});
test('look input supports aiming at weapons close to the feet',()=>{assert.equal(sanitize({pitch:-1.2,aimPitch:-1.2}).pitch,-1.2);assert.equal(sanitize({pitch:-1.2,aimPitch:-1.2}).aimPitch,-1.2);});
test('repeated pickup requests never collect a neighbouring item on a later tick',()=>{const {m,p}=fixture();m.input(p.id,{pickupRequest:request(),slot:0});m.tick(.03);assert.equal(p.inventory.filter(Boolean).length,1);m.tick(.03);assert.equal(p.inventory.filter(Boolean).length,1);assert.equal(m.pickups[0].id,'neighbour');});
test('a valid eye ray can pick a visible gun over low cover without a second torso ray',()=>{const {m,p}=fixture();m.world.obstacles=[{min:[-.2,0,-.3],max:[.2,1.4,-.1]}];assert.equal(m.interact(p,sanitize({pickupRequest:request()})),true);assert.equal(p.inventory[0].type,'ar_sentinel');});

// Measured native AR triangle from 6.8 m/s movement with 550 ms snapshots.
function movingGuest(){const m=new Match({height:()=>0,obstacles:[],resources:[],chests:[]},['a','b']),p=m.players[0];m.phase='playing';p.air='landed';p.p=[20.51333333333333,0,0];m.elapsed=3.0166666666666666;m.input(p.id,{x:1,slot:0});for(let n=0;n<3;n++)m.tick(.05);m.pickups=[{id:'displayed',type:'ar',count:1,x:21.043894708204867,y:0,z:-1.5}];return {m,p,request:{revision:1,id:'displayed',round:m.round,time:2.783333333333333,origin:[20.554456083076403,1.72,0],point:[21.030086373150432,.3332783124920823,-1.4576811033738575]}};}
test('a moving guest can collect its actual displayed triangle despite snapshot smoothing lag',()=>{const {m,p,request}=movingGuest();assert.ok(Math.abs(p.p[0]-request.origin[0])>.7);assert.equal(m.interact(p,sanitize({pickupRequest:request})),true);assert.equal(p.inventory[0].type,'ar');});
test('expired and previous-round display requests cannot collect a gun',()=>{for(const patch of [{time:0},{round:0},{round:2},{time:10}]){const {m,p,request}=movingGuest();request.origin=[p.p[0],1.72,p.p[2]];assert.equal(m.interact(p,sanitize({pickupRequest:{...request,...patch}})),false);assert.equal(m.pickups.length,1);}});
test('lag compensation cannot collect from a historical origin through current intervening cover',()=>{const {m,p,request}=movingGuest();m.world.obstacles=[{min:[21.15,0,-.8],max:[21.4,3,-.6]}];assert.equal(m.interact(p,sanitize({pickupRequest:request})),false);});
test('pickup eye history stays bounded and does not enter network snapshots',()=>{const {m,p}=movingGuest();m.input(p.id,{slot:0});for(let n=0;n<200;n++)m.tick(.05);assert.ok(p.pickupEyeHistory.length<=80);assert.ok(p.pickupEyeHistory[0].time>=m.elapsed-2);assert.equal('pickupEyeHistory' in m.snapshot().players[0],false);});
test('late requests validate the captured spinning model pose rather than its later rotation',()=>{const {m,p}=fixture();m.pickups=[{id:'displayed',type:'ar',x:0,y:0,z:-2,count:1}];const item=m.pickups[0],pose=groundWeaponPose(item,0),x=-.04,z=.48,point=[x*Math.cos(pose.rotation)+z*Math.sin(pose.rotation),pose.height+.2,item.z-x*Math.sin(pose.rotation)+z*Math.cos(pose.rotation)];m.elapsed=2;assert.equal(pickupPointInside(item,point,m.elapsed),false);assert.equal(m.interact(p,sanitize({pickupRequest:{...request(),point}})),true);});
