import test from 'node:test';import assert from 'node:assert/strict';
import {loadPlatformMap,platformLayout,platformSupportHeight} from '../public/platform23-map.js';
import {Match} from '../public/simulation.js';import {chestLoot} from '../public/loot-system.js';import {WEAPON_PROFILES} from '../public/weapon-system.js';
await loadPlatformMap();const world=platformLayout();
const playing=()=>{const m=new Match(world,['a','b']);m.phase='playing';for(const p of m.players){p.air='landed';p.p=[35,1.5,17];p.grounded=true;}return m;};
test('courtyard gaps and approaches to the southern corridor have real supported ground',()=>{for(const x of [-35,-20,0,20,35])for(const z of [27,30,34,38,42])assert.ok(platformSupportHeight(x,z,2,.01)>-1,`${x},${z} cannot be a sky hole`);assert.equal(world.obstacles.some(b=>b.type==='playerclip'||b.type==='boundary'),false);});
test('Platform 23 rejects building, harvesting and shockwaves at the authority',()=>{const m=playing(),p=m.players[0];p.materials={wood:100,stone:100};p.items.shockwave=2;assert.equal(m.harvest(p,{yaw:0}),false);assert.equal(m.throwShockwave(p,{yaw:0}),false);m.input('a',{slot:6,fire:true});m.tick(.05);assert.equal(m.structures.length,0);assert.notEqual(p.slot,6);for(const c of world.chests)for(let r=1;r<8;r++)assert.equal(chestLoot(c,r,world).some(i=>i.type==='shockwave'),false);});
test('Ctrl toggles crouch and cancels a running slide without holding Shift',()=>{const m=playing(),p=m.players[0];m.input('a',{crouchRevision:1});m.tick(.05);assert.equal(p.crouching,true);m.input('a',{crouchRevision:1});m.tick(.05);assert.equal(p.crouching,true);m.input('a',{crouchRevision:2});m.tick(.05);assert.equal(p.crouching,false);m.input('a',{z:1,sprint:true,crouchRevision:2});m.tick(.05);m.input('a',{z:1,sprint:true,crouchRevision:3});m.tick(.05);assert.equal(p.sliding,true);m.input('a',{crouchRevision:3});m.tick(.05);assert.equal(p.sliding,true);m.input('a',{crouchRevision:4});m.tick(.05);assert.equal(p.sliding,false);assert.equal(p.crouching,false);});
test('all weapon profiles apply lower damage to both score and elimination modes',()=>{for(const [id,old]of Object.entries({ar:31,shotgun:14,smg:19,sniper:116}))assert.ok(WEAPON_PROFILES[id].damage<old*.8);});

test('cancelling a slide preserves head clearance under a low ceiling',()=>{const roof={min:[-5,1.5,-5],max:[5,2,5]};const m=new Match({height:()=>0,obstacles:[roof],resources:[],chests:[],pois:[]},['a','b']);m.phase='playing';const p=m.players[0];Object.assign(p,{air:'landed',p:[0,0,0],sliding:true,crouching:true,slideSpeed:9,slideDir:[0,1],lastCrouchRevision:1});m.input('a',{crouchRevision:2});m.tick(.05);assert.equal(p.sliding,false);assert.equal(p.crouching,true);});

test('both courtyards walk continuously toward the southern connection without falling or freezing',()=>{for(const x of [-35,35]){const m=playing(),p=m.players[0];p.p=[x,1.5,17];for(let tick=0;tick<65;tick++){m.input('a',{yaw:Math.PI,z:1});m.tick(.05);assert.ok(Number.isFinite(p.p[1]));assert.ok(p.p[1]>-1);assert.equal(p.hp,100);}assert.ok(p.p[2]>37,'route must cross more than twenty metres of connected ground');}});
