import test from 'node:test';import assert from 'node:assert/strict';import {Match,placement,validBuild,sanitize,ground} from '../public/simulation.js';
const world={height:()=>0,obstacles:[]};
const landAll=m=>{for(const p of m.players){p.p[1]=0;p.air='landed';p.vy=0;}m.phase='playing';};
test('build follows facing in four directions and allows upper-level chains',()=>{const p={p:[0,0,0]};for(const [yaw,x,z] of [[0,0,-5],[Math.PI/2,-5,0],[Math.PI,0,5],[-Math.PI/2,5,0]]){let s=placement(p,{yaw,slot:3},world);assert.ok(Math.abs(s.x-x)<.001&&Math.abs(s.z-z)<.001);assert.equal(validBuild(s,[],[p],world),true);}const ramp={x:0,z:0,y:0,angle:0,type:3};assert.equal(ground(0,2.4,0,[ramp],world)>.05,true);assert.equal(validBuild({x:0,z:-5,y:3.6,type:3,angle:0},[ramp],[],world),true);});
test('four-player drop supports jump, freefall, canopy deployment and landing',()=>{const m=new Match(world,['a','b','c','d']);assert.equal(m.phase,'waiting');m.launchDrop();m.input('a',{jump:true,yaw:0});m.tick(.05);assert.equal(m.players[0].air,'freefall');m.input('a',{jump:false,yaw:0});m.tick(.05);m.input('a',{jump:true,yaw:0});m.tick(.05);assert.equal(m.players[0].air,'glider');for(let i=0;i<900&&!['countdown','playing'].includes(m.phase);i++)m.tick(.05);assert.ok(['countdown','playing'].includes(m.phase));assert.ok(m.players.every(p=>p.air==='landed'));});
test('multiplayer round ends only when one of four players remains',()=>{const m=new Match(world,['a','b','c','d']);landAll(m);m.disconnect('b');assert.equal(m.phase,'playing');m.disconnect('c');assert.equal(m.phase,'playing');m.disconnect('d');assert.equal(m.phase,'roundover');assert.equal(m.winner,0);assert.equal(m.scores[0],1);});
test('host simulates hits and ammo in multiplayer combat',()=>{const m=new Match(world,['a','b','c']);landAll(m);m.players[0].p=[0,0,0];m.players[1].p=[0,0,-10];m.players[2].p=[20,0,20];const before=m.players[0].ammo;for(let i=0;i<20&&m.players[1].hp>0;i++){m.input('a',{yaw:0,fire:true});m.tick(.16);}assert.equal(m.players[1].hp,0);assert.ok(m.players[0].ammo<before);assert.equal(m.phase,'playing');});
test('wall blocks bullets and loses durability',()=>{const m=new Match(world,['a','b']);landAll(m);m.players[0].p=[0,0,0];m.players[1].p=[0,0,-10];m.structures=[{x:0,z:-5,y:0,angle:0,type:2,hp:150}];m.input('a',{yaw:0,fire:true});m.tick(.03);assert.equal(m.players[1].shield,100);assert.equal(m.structures[0].hp,116);});
test('same fire input places a wall and duplicates cost nothing',()=>{const m=new Match(world,['a','b'],'town');landAll(m);m.players[0].p=[0,0,0];m.input('a',{yaw:0,slot:2,fire:true});m.tick(.03);assert.equal(m.structures.length,1);assert.equal(m.players[0].material,140);for(let i=0;i<20;i++){m.input('a',{yaw:0,slot:2,fire:true});m.tick(.03);}assert.equal(m.structures.length,1);assert.equal(m.players[0].material,140);});
test('invalid inputs cannot introduce NaN or unbounded movement',()=>{const i=sanitize({x:Infinity,yaw:NaN,z:500,slot:888});assert.equal(i.x,0);assert.equal(i.yaw,0);assert.equal(i.z,1);assert.equal(i.slot,1);});
test('waiting phase prevents early movement, firing, and builds',()=>{const m=new Match(world,['a','b']);const before=structuredClone(m.snapshot());m.input('a',{z:1,fire:true,slot:2});for(let i=0;i<100;i++)m.tick(.03);assert.deepEqual(m.snapshot(),before);m.launchDrop();assert.equal(m.phase,'bus');});
test('first player to five round wins completes the match',()=>{const m=new Match(world,['a','b','c']);for(let r=0;r<5;r++){landAll(m);m.players[1].hp=0;m.players[1].eliminated=true;m.players[2].hp=0;m.players[2].eliminated=true;m.checkRoundEnd();assert.equal(m.scores[0],r+1);if(r<4)m.startRound(false);}assert.equal(m.phase,'done');});

test('disconnected players are removed before the next round and never respawn as ghosts',()=>{const m=new Match(world,['a','b','c']);landAll(m);m.disconnect('c');assert.equal(m.players.find(p=>p.id==='c').hp,0);m.startRound(false);assert.deepEqual(m.ids,['a','b']);assert.equal(m.players.some(p=>p.id==='c'),false);});
test('a disconnect during pre-drop waiting shrinks the required participant roster',()=>{const m=new Match(world,['a','b','c']);assert.equal(m.phase,'waiting');m.disconnect('c');assert.deepEqual(m.ids,['a','b']);assert.equal(m.players.length,2);});
