import test from 'node:test';import assert from 'node:assert/strict';import {Match,placement,validBuild,sanitize,ground} from '../public/simulation.js';
const world={height:()=>0,obstacles:[]};
test('build follows facing in four directions and allows upper-level chains',()=>{const p={p:[0,0,0]};for(const [yaw,x,z] of [[0,0,-5],[Math.PI/2,-5,0],[Math.PI,0,5],[-Math.PI/2,5,0]]){let s=placement(p,{yaw,slot:3},world);assert.ok(Math.abs(s.x-x)<.001&&Math.abs(s.z-z)<.001);assert.equal(validBuild(s,[],[p],world),true);}const ramp={x:0,z:0,y:0,angle:0,type:3};assert.equal(ground(0,2.4,0,[ramp],world)>.05,true);assert.equal(validBuild({x:0,z:-5,y:3.6,type:3,angle:0},[ramp],[],world),true);});
test('host simulates hits, rounds, victory, and ammo',()=>{const m=new Match(world,['a','b']);for(let round=0;round<5;round++){for(let i=0;i<92;i++)m.tick(1/30);m.players[0].p=[0,0,0];m.players[1].p=[0,0,-10];for(let i=0;i<100&&m.phase==='playing';i++){m.input('a',{yaw:0,fire:true});m.tick(1/30);}assert.equal(m.scores[0],round+1);assert.ok(m.players[0].ammo<30);if(round<4){for(let i=0;i<92;i++)m.tick(1/30);}}assert.equal(m.phase,'done');});
test('wall blocks bullets and loses durability',()=>{const m=new Match(world,['a','b']);m.phase='playing';m.players[0].p=[0,0,0];m.players[1].p=[0,0,-10];m.structures=[{x:0,z:-5,y:0,angle:0,type:2,hp:150}];m.input('a',{yaw:0,fire:true});m.tick(.03);assert.equal(m.players[1].shield,100);assert.equal(m.structures[0].hp,116);});
test('same fire input places a wall and duplicates cost nothing',()=>{const m=new Match(world,['a','b'],'town');m.phase='playing';m.players[0].p=[0,0,0];m.input('a',{yaw:0,slot:2,fire:true});m.tick(.03);assert.equal(m.structures.length,1);assert.equal(m.players[0].material,140);for(let i=0;i<20;i++){m.input('a',{yaw:0,slot:2,fire:true});m.tick(.03);}assert.equal(m.structures.length,1);assert.equal(m.players[0].material,140);});
test('invalid inputs cannot introduce NaN or unbounded movement',()=>{const i=sanitize({x:Infinity,yaw:NaN,z:500,slot:888});assert.equal(i.x,0);assert.equal(i.yaw,0);assert.equal(i.z,1);assert.equal(i.slot,1);});

test('waiting phase prevents early movement, firing, and builds',()=>{const m=new Match(world,['a','b']);m.phase='waiting';const before=structuredClone(m.snapshot());m.input('a',{z:1,fire:true,slot:2});for(let i=0;i<100;i++)m.tick(.03);assert.deepEqual(m.snapshot(),before);m.phase='countdown';m.timer=.01;m.tick(.02);assert.equal(m.phase,'playing');});
