import assert from 'node:assert/strict';
import {checkBuilding} from './browser-building.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {chromium} from 'playwright';
const url=process.env.GAME_TEST_URL||'http://127.0.0.1:4174',artifacts=process.env.GAME_ARTIFACTS||'/workspace/fortmulti-artifacts';await mkdir(artifacts,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||(existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined),headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--disable-dev-shm-usage','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows']});
const context=await browser.newContext({viewport:{width:1280,height:720}}),errors=[],checks=[];
async function open(){const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.__sampledAudio=[];const start=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args){const entry={duration:this.buffer?.duration,rate:this.playbackRate.value,offset:args[1]||0,ended:false};window.__sampledAudio.push(entry);this.addEventListener('ended',()=>entry.ended=true);return start.apply(this,args);};});await p.goto(url+'/?local=1');await p.waitForFunction(()=>Boolean(window.Game));await p.evaluate(async()=>{const [{Connection},{Match}]=await Promise.all([import('/network.js'),import('/simulation.js')]);const originalOpen=Connection.prototype.open;Connection.prototype.open=async function(...args){await originalOpen.apply(this,args);window.__testConnection=this;};const startRound=Match.prototype.startRound;Match.prototype.startRound=function(...args){const result=startRound.apply(this,args);window.__testMatch=this;return result;};const move=window.Game.moveInventory.bind(window.Game);window.__moveObservations=[];window.__inventoryAckIds=[];const ack=window.Game.ackInventory.bind(window.Game);window.Game.ackInventory=value=>{window.__inventoryAckIds.push(value.id);ack(value);};window.Game.moveInventory=(from,to)=>{const start=performance.now(),accepted=move(from,to);window.__moveObservations.push({accepted,duration:performance.now()-start,ids:window.Game.inventoryState().inventory.map(w=>w?.id||null)});return accepted;};});return p;}
async function drag(page,from,to,{capture=false}={}){const a=await page.locator(`[data-inventory-cards] [data-inventory-slot="${from}"]`).boundingBox(),b=to?await page.locator(`[data-inventory-cards] [data-inventory-slot="${to}"]`).boundingBox():{x:5,y:5,width:1,height:1};await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:6});if(capture)await page.screenshot({path:artifacts+'/inventory-drag.png'});await page.mouse.up();}
try{
 const host=await open(),guest=await open();await host.locator('#create').click();await host.waitForFunction(()=>window.__testConnection?.connected);const code=await host.evaluate(()=>window.__testConnection.code);await guest.locator('.test-tools summary').first().click();await guest.locator('#code').fill(code);await guest.locator('#join').click();await host.waitForFunction(()=>document.getElementById('party-count').textContent.startsWith('2'));await guest.waitForFunction(()=>window.__testConnection?.host);await host.locator('#ready').click();await guest.locator('#ready').click();await host.waitForFunction(()=>Boolean(window.__testMatch));
 await host.evaluate(()=>{const m=window.__testMatch;m.phase='playing';m.players.forEach((p,i)=>{p.p=[i*30,window.Game.world.height(i*30,62),62];p.air='landed';p.deploymentState='match_active';p.hp=100;p.slot=0;p.inventory=[{id:p.id+':ar',type:'ar',ammo:17},{id:p.id+':shotgun',type:'shotgun',ammo:3},{id:p.id+':smg',type:'smg',ammo:23},{id:p.id+':sniper',type:'sniper',ammo:2},null];p.items={shield:3,health:1,shockwave:2};p.materials={wood:100,stone:100};});});await guest.waitForFunction(()=>window.Game.inventoryState().inventory.filter(Boolean).length===4);
 await guest.keyboard.press('1');await guest.waitForFunction(()=>window.Game.input().slot===1);await guest.keyboard.press('Tab');await guest.locator('#inventory-menu').waitFor({state:'visible'});assert.equal(await guest.locator('[data-inventory-slot]').count(),5);await guest.waitForFunction(()=>document.querySelectorAll('.inventory-card-art img').length===4);await guest.screenshot({path:artifacts+'/inventory-populated.png'});checks.push('Five-slot Tab menu, real-model previews and separate utilities');
 await guest.waitForFunction(()=>document.querySelectorAll('.weapon-slots img').length===4&&[...document.querySelectorAll('.weapon-slots img')].every(image=>image.complete&&image.naturalWidth>0));
 assert.equal(await guest.evaluate(()=>[...document.querySelectorAll('.weapon-slots [data-slot]')].every(button=>{const slot=button.dataset.slot,quick=button.querySelector('img'),card=document.querySelector(`[data-inventory-cards] [data-inventory-slot="${slot}"] img`);return quick?.src===card?.src;})),true,'quick slots must show the matching model thumbnail');
 await guest.evaluate(async()=>{const originals=[...document.querySelectorAll('.weapon-slots img')];await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));if(originals.some((image,i)=>image!==document.querySelectorAll('.weapon-slots img')[i]))throw Error('HUD recreated cached preview nodes during unchanged frames');});
 checks.push('Quick slots match real inventory previews and reuse cached image nodes');
 await guest.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{code:'Tab',repeat:true,bubbles:true})));assert.equal(await guest.locator('#inventory-menu').isVisible(),true);await guest.keyboard.press('Space');await guest.keyboard.press('ArrowLeft');await guest.keyboard.press('Space');await guest.waitForFunction(()=>window.Game.inventoryState().pending.length===0);assert.equal(await guest.evaluate(()=>window.Game.inventoryState().inventory[0]),null);await guest.keyboard.press('Space');await guest.keyboard.press('ArrowRight');await guest.keyboard.press('Space');await guest.waitForFunction(()=>window.Game.inventoryState().pending.length===0);checks.push('Keyboard move controls are reachable; held Tab does not flicker');
 const initial=await guest.evaluate(()=>window.Game.inventoryState().inventory.map(w=>w?.id||null));await drag(guest,1,2,{capture:true});assert.deepEqual(await guest.evaluate(()=>window.__moveObservations.at(-1).ids.slice(0,2)),[initial[1],initial[0]]);await guest.waitForFunction(()=>window.Game.inventoryState().pending.length===0);assert.equal(await guest.evaluate(()=>window.Game.input().slot),2);assert.ok(await guest.evaluate(()=>window.__inventoryAckIds.length>0),'Explicit network acknowledgement reaches the guest');checks.push('Occupied swap is immediate and preserves equipped instance');
 await drag(guest,2,5);await guest.waitForFunction(()=>window.Game.inventoryState().pending.length===0);assert.equal(await guest.evaluate(()=>window.Game.inventoryState().inventory[4].id),initial[0]);assert.equal(await guest.evaluate(()=>window.Game.inventoryState().inventory[1]),null);assert.equal(await guest.evaluate(()=>window.Game.input().slot),5);checks.push('Empty-slot move and authoritative acknowledgement');
 const before=await guest.evaluate(()=>window.Game.inventoryState().inventory.map(w=>w?.id||null));await drag(guest,5,null);assert.deepEqual(await guest.evaluate(()=>window.Game.inventoryState().inventory.map(w=>w?.id||null)),before);checks.push('Outside release cancels without item loss');
 const cancelBox=await guest.locator('[data-inventory-cards] [data-inventory-slot="5"]').boundingBox();await guest.mouse.move(cancelBox.x+50,cancelBox.y+50);await guest.mouse.down();await guest.mouse.move(cancelBox.x-80,cancelBox.y+80);await guest.evaluate(()=>document.querySelector('[data-inventory-cards]').dispatchEvent(new PointerEvent('pointercancel',{pointerId:1,bubbles:true})));await guest.mouse.up();assert.deepEqual(await guest.evaluate(()=>window.Game.inventoryState().inventory.map(w=>w?.id||null)),before);assert.equal(await guest.locator('[data-inventory-slot]').count(),5);await guest.evaluate(()=>window.dispatchEvent(new Event('blur')));await guest.locator('#inventory-menu').waitFor({state:'hidden'});await guest.keyboard.press('Tab');checks.push('Pointer cancellation and focus loss clear drag state without losing weapons');
 // Duplicate action delivery exercises the real app message handler and host deduplication.
 await guest.evaluate(()=>{const c=window.__testConnection,send=c.send;c.send=function(type,data,to){send.call(this,type,data,to);if(type==='inventory-move')send.call(this,type,data,to);};});
 await guest.evaluate(()=>{for(let n=0;n<12;n++)window.Game.moveInventory(n%2?2:5,n%2?5:2);});await guest.waitForFunction(()=>window.Game.inventoryState().pending.length===0,{timeout:20000});assert.deepEqual(await guest.evaluate(()=>window.Game.inventoryState().inventory.map(w=>w?.id||null)),before);assert.equal(await host.evaluate(id=>window.__testMatch.players.find(p=>p.id===id).inventory[4].type,await guest.evaluate(()=>window.__testConnection.id)),'ar');assert.deepEqual(await guest.evaluate(()=>window.Game.inventoryState().inventory.map(w=>w?.ammo??null)),[3,null,23,2,17]);checks.push('Rapid queued moves converge over real BroadcastChannel; duplicate delivery is harmless');
 await guest.keyboard.press('Tab');await guest.keyboard.press('z');await guest.keyboard.press('Tab');await drag(guest,5,2);await guest.waitForFunction(()=>window.Game.inventoryState().pending.length===0);await guest.keyboard.press('Tab');await guest.keyboard.press('q');assert.equal(await guest.evaluate(()=>window.Game.input().slot),2,'Q returns to the same weapon after a utility-mode rearrange');await guest.keyboard.press('Tab');await drag(guest,2,5);await guest.waitForFunction(()=>window.Game.inventoryState().pending.length===0);checks.push('Q preserves last weapon identity across rearrangement while building');
 await guest.evaluate(()=>{const send=window.Duel.moveInventory;window.Duel.moveInventory=()=>{};window.Game.moveInventory(5,2);window.Game.clear();if(window.Game.inventoryState().pending.length!==1)throw new Error('Opening match menu discarded a queued inventory move');window.Duel.moveInventory=send;send(window.Game.inventoryState().pending[0]);});await guest.waitForFunction(()=>window.Game.inventoryState().pending.length===0);await guest.keyboard.press('Tab');await drag(guest,2,5);await guest.waitForFunction(()=>window.Game.inventoryState().pending.length===0);checks.push('Opening match menu preserves in-flight inventory operations');
 await guest.keyboard.press('Escape');await guest.locator('#inventory-menu').waitFor({state:'hidden'});assert.equal(await guest.locator('#match-actions').isVisible(),false);checks.push('Escape closes inventory before match menu');
 for(const [key,label]of [['5','STRIKER AR'],['1','THUNDER SHOTGUN'],['3','RAPTOR SMG'],['4','EAGLE-EYE SNIPER'],['z','WALL'],['v','RAMP'],['0','FIELD PICKAXE'],['7','SHIELD CELL'],['8','MED KIT'],['9','SHOCKWAVE']]){await guest.keyboard.press(key);await guest.waitForFunction(label=>document.getElementById('weaponlabel').textContent.includes(label),label);}checks.push('All arbitrary weapon keys and separate building/pickaxe/consumable controls');
 await guest.keyboard.press('5');await guest.waitForFunction(()=>window.Game.pose().weapon==='ar');if(await guest.locator('#resume-control').isVisible())await guest.locator('#resume-control').click();await guest.screenshot({path:artifacts+'/gameplay-ar.png'});
 await guest.keyboard.press('Tab');await guest.keyboard.down('w');await guest.mouse.click(900,570);assert.equal(await guest.evaluate(()=>window.Game.input().x||window.Game.input().z||window.Game.input().fire||window.Game.input().interact),false);await guest.keyboard.up('w');await guest.keyboard.press('Tab');checks.push('Inventory suppresses movement and combat inputs');
 // Real R input, snapshot-event dispatch and audio use the actual two-tab transport.
 await guest.evaluate(()=>window.Game.startAudio());await guest.keyboard.press('1');await guest.waitForFunction(()=>window.Game.pose().weapon==='shotgun');await host.waitForFunction(id=>window.__testMatch.players.find(p=>p.id===id).equip<=0,await guest.evaluate(()=>window.__testConnection.id));
 await guest.keyboard.press('r',{delay:100});await guest.waitForFunction(()=>window.__sampledAudio.some(v=>Math.abs(v.duration-2.7)<.001));
 assert.equal(await guest.evaluate(()=>window.__sampledAudio.filter(v=>Math.abs(v.duration-2.7)<.001).length),1,'one authoritative reload event plays one sample');
 await guest.waitForFunction(()=>window.Game.pose().reload===0&&window.Game.inventoryState().inventory[0].ammo===6,{timeout:10000});
 await guest.waitForFunction(()=>window.__sampledAudio.filter(v=>Math.abs(v.duration-2.7)<.001).every(v=>v.ended));checks.push('Real R press plays one shotgun reload across guest/host snapshots and completes with ammo refill');
 const reloadGuestId=await guest.evaluate(()=>window.__testConnection.id);await host.evaluate(id=>{window.__testMatch.players.find(p=>p.id===id).inventory[0].ammo=2;},reloadGuestId);
 await guest.waitForFunction(()=>window.Game.inventoryState().inventory[0].ammo===2);await guest.keyboard.press('r',{delay:100});await guest.waitForFunction(()=>window.__sampledAudio.filter(v=>Math.abs(v.duration-2.7)<.001).length===2);
 await guest.keyboard.press('5');await guest.waitForFunction(()=>window.Game.pose().weapon==='ar'&&window.Game.pose().reload===0);await guest.waitForFunction(()=>window.__sampledAudio.filter(v=>Math.abs(v.duration-2.7)<.001).every(v=>v.ended));checks.push('Switching guns cancels the authoritative shotgun reload and fades its audio');
 // Fixture data places a chest in open terrain; E input still passes through real guest/host networking.
 const guestId=await guest.evaluate(()=>window.__testConnection.id),chest=await host.evaluate(async id=>{const m=window.__testMatch,p=m.players.find(p=>p.id===id);p.p=[90,m.world.height(90,62),62];p.yaw=0;p.slot=0;p.input.slot=0;const chest={id:'browser-chest',x:90,y:p.p[1],z:60};m.chests.push(chest);const {createEntityGrid}=await import('/resource-system.js');m.chestGrid=createEntityGrid(m.chests);return chest;},guestId);await guest.evaluate(chest=>{window.Game.world.chests.push(chest);window.Game.look(0);},chest);await guest.keyboard.press('0');await guest.waitForFunction(()=>Math.abs(window.Game.pose().p[0]-90)<.5);await guest.keyboard.down('e');await host.waitForFunction(id=>window.__testMatch.players.find(p=>p.id===id).chestHold?.elapsed>.05,guestId,{polling:20});await guest.keyboard.up('e');await host.waitForFunction(id=>window.__testMatch.players.find(p=>p.id===id).chestHold===null,guestId);assert.equal(await host.evaluate(()=>window.__testMatch.openedChests.has('browser-chest')),false);checks.push('Release-E cancels networked chest progress');
 await guest.keyboard.down('e');await host.waitForFunction(()=>window.__testMatch.openedChests.has('browser-chest'),{timeout:20000});const lootCount=await host.evaluate(()=>window.__testMatch.pickups.length);await guest.keyboard.up('e');assert.ok(lootCount>=2);assert.equal(await host.evaluate(()=>window.__testMatch.events.filter(e=>e.type==='chest'&&e.chest==='browser-chest').length),1);checks.push('Networked held-E completion opens chest exactly once');
 await guest.waitForFunction(()=>window.Game.pose().chestHold===null);if(await guest.locator('#resume-control').isVisible())await guest.locator('#resume-control').click();await guest.evaluate(()=>window.Game.look(0,-.45));await guest.screenshot({path:artifacts+'/ground-loot.png'});

 // Real keyboard taps must survive guest networking and host tick boundaries.
 await guest.evaluate(()=>window.Game.look(0));await host.evaluate(id=>{const p=window.__testMatch.players.find(p=>p.id===id);const w=window.__testMatch.world;let route=null;for(let x=-220;x<=220&&!route;x+=10)for(let z=-220;z<=220;z+=10){const y=w.height(x,z);if(y<0)continue;if(Array.from({length:9},(_,n)=>w.height(x,z-n*5)).some(h=>Math.abs(h-y)>.05))continue;if(w.obstacles.some(b=>b.min[0]<x+3&&b.max[0]>x-3&&b.min[2]<z+3&&b.max[2]>z-43))continue;route=[x,y,z];break;}if(!route)throw Error('No flat supported sprint route');p.p=route;p.vy=0;p.impulse=[0,0];p.grounded=true;p.sliding=false;p.crouching=false;p.crouchRequested=false;},guestId);
 await guest.keyboard.press('ControlLeft');await host.waitForFunction(id=>window.__testMatch.players.find(p=>p.id===id).crouching,guestId);
 assert.equal(await guest.evaluate(()=>window.Game.input().crouch),false,'Ctrl has been released');
 await guest.waitForTimeout(500);assert.equal(await host.evaluate(id=>window.__testMatch.players.find(p=>p.id===id).crouching,guestId),true);
 await guest.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{code:'ControlLeft',repeat:true,bubbles:true})));
 assert.equal(await host.evaluate(id=>window.__testMatch.players.find(p=>p.id===id).crouching,guestId),true);
 await guest.keyboard.up('ControlLeft');await guest.keyboard.press('ControlLeft');await host.waitForFunction(id=>!window.__testMatch.players.find(p=>p.id===id).crouching,guestId);checks.push('Quick Ctrl tap toggles crouch, survives key release, and ignores auto-repeat');
 await guest.keyboard.down('w');await guest.keyboard.down('ShiftLeft');
 await host.waitForFunction(id=>{const p=window.__testMatch.players.find(p=>p.id===id);return p.sprinting&&p.moveSpeed>7.5;},guestId);
 assert.equal(await host.evaluate(id=>{const p=window.__testMatch.players.find(p=>p.id===id);return p.sliding||p.crouching;},guestId),false,'Shift must only run');
 await guest.keyboard.up('ShiftLeft');
 await host.waitForFunction(id=>{const p=window.__testMatch.players.find(p=>p.id===id);return !p.sprinting&&!p.sliding&&!p.crouching&&p.moveSpeed>3;},guestId);
 await guest.keyboard.press('ShiftRight');await guest.waitForTimeout(250);
 assert.equal(await host.evaluate(id=>{const p=window.__testMatch.players.find(p=>p.id===id);return p.sliding||p.crouching;},guestId),false,'a quick Shift tap must never slide');
 checks.push('Both Shift keys only run; releasing Shift returns to walking without a crouch or slide');
 await guest.keyboard.down('ShiftRight');await host.waitForFunction(id=>window.__testMatch.players.find(p=>p.id===id).sprinting,guestId);
 await guest.keyboard.press('ControlRight');
 await guest.keyboard.up('ShiftRight');await guest.keyboard.up('w');
 assert.equal(await guest.evaluate(()=>Boolean(window.Game.input().sprint||window.Game.input().crouch||window.Game.input().z)),false,'all slide keys have been released');
 await host.waitForFunction(id=>window.__testMatch.players.find(p=>p.id===id).sliding,guestId,{polling:20});
 await host.waitForFunction(id=>{const p=window.__testMatch.players.find(p=>p.id===id);return !p.sliding&&!p.crouching;},guestId);
 checks.push('A quick Ctrl tap while running starts a knee slide that completes standing with all keys released');
 await checkBuilding(host,guest,guestId,artifacts,checks);
 await guest.setViewportSize({width:800,height:600});await guest.keyboard.press('Tab');await guest.screenshot({path:artifacts+'/inventory-compact.png'});assert.equal(await guest.evaluate(()=>document.getElementById('inventory-menu').scrollWidth>innerWidth),false);await guest.keyboard.press('Escape');
 assert.deepEqual(errors,[],'Browser runtime errors');const observations=await guest.evaluate(()=>window.__moveObservations);await writeFile(artifacts+'/browser-results.json',JSON.stringify({checks,errors,moves:observations},null,2));console.log(JSON.stringify({passed:checks.length,checks,maxLocalMoveMs:Math.max(...observations.map(o=>o.duration)),errors},null,2));
}catch(error){
 await writeFile(artifacts+'/failure-results.json',JSON.stringify({error:String(error),checks,pages:await Promise.all(context.pages().map(p=>p.evaluate(()=>({pose:window.Game?.pose(),input:window.Game?.input(),host:window.__testMatch?.snapshot()})).catch(e=>({error:String(e)}))))},null,2));
 throw error;
}finally{await browser.close();}
